### ISSUE TITLE
Multi-Botting?

### ISSUE THREAD

**Issue by MrFiend179** [MrFiend179/Flubel-Boove#2]
in v1.3.0

**Comment by tmquan2508** [comment]
yes, but please update your code, it isn't work now when I run it

**Comment by MrFiend179** [comment]
> yes, but please update your code, it isn't work now when I run it

Can youu please elaborate more? Like in what sense it isnt working, the app stops responding or are you trying to compile the code to make it run?

**Comment by tmquan2508** [comment]
it has this error 
"Skip checkForUpdates because application is not packed and dev update config is not forced
checkForUpdatesAndNotify called, downloadPromise is null
(node:4824) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (C:\Users\tmqua\Desktop\Flubel-Boove\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:4824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[11308:0205/125943.509:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is"
 and the tab when created is transparent, maybe you haven't updated a file you edited to github

**Comment by tmquan2508** [comment]
Have any update ?

**Comment by MrFiend179** [comment]
> it has this error 
> "Skip checkForUpdates because application is not packed and dev update config is not forced
> checkForUpdatesAndNotify called, downloadPromise is null
> (node:4824) UnhandledPromiseRejectionWarning: Error: Could not connect
>     at Socket.onerror (C:\Users\tmqua\Desktop\Flubel-Boove\node_modules\discord-rpc\src\transports\ipc.js:32:16)
>     at Object.onceWrapper (node:events:642:26)
>     at Socket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> (Use `electron --trace-warnings ...` to show where the warning was created)
> (node:4824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [11308:0205/125943.509:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is"
>  and the tab when created is transparent, maybe you haven't updated a file you edited to github

Yes,

1. The first error encountered is regarding the apps auto updater which isn't working because the app isn't packaged yet and is in development environment

2. The second error encountered is regarding the discord rich presence it's due to discord app not running on the system

And the tab that is transparent is weird, I'll look into it, as for me the code is working fine. I'll get back to you for the transparent tabs once I figure the issue out.

**Comment by MrFiend179** [comment]
> Have any update ?

The tab being invisible may be caused due to two things

1. Libraries version, since this apps code is old, I haven't updated the libraries to their latest version

2. Due to slow system, make sure to check your system meets minimum criteria listed at https://www.flubel.tech/flubelboove

Otherwise it's working fine for me, I even tried it on other pc
